### ISSUE TITLE
Doubt on how to use it in practice

### ISSUE THREAD

**Issue by lucasbr15** [haoheliu/torchsubband#5]
Hello how are you?

I'm curious to know how to use torchsubband in practice,

I would like to know if it is already integrated in MSS-Challenge-CWS-PResUNet and I would like to know if it would also be possible to use it in other music source separation,

In the "simple example" it was not very clear, this tool decomposes a song.wav would that be?

Sorry but I'm totally new to the torchsubband functionality,

Sorry and thank you very much since,

Regards,
Lucas Rodrigues.

**Comment by haoheliu** [comment]
Torchsubband is a tool that computes a new representation of the audio. It's definitely usable in other architecture as long as you design proper architecture. 

I build Torchsubband after MSS-Challenge-CWS-PResUNet, so do not directly use it in the repo. But similar subband logic is applied.

Subband decomposition is quite useful in a lot of applications in terms of reducing complexity and improving performance:

[Multi-band MelGan for fast and high quality vocoding](https://arxiv.org/abs/2005.05106)
[DurIAN: Duration Informed Attention Network for Speech Synthesis.](https://www.isca-speech.org/archive_v0/Interspeech_2020/pdfs/2968.pdf)
[FeatherWave: An efficient high-fidelity neural vocoder with multi-band linear prediction](https://arxiv.org/abs/2005.05551)
[Bytedance official music source separation repo](https://github.com/bytedance/music_source_separation/blob/master/bytesep/models/resunet_subbandtime.py)

**Comment by playdasegunda** [comment]
thanks
